import { categories, type Platform } from "./helpdesk-data";

export type Difficulty = "Easy" | "Medium" | "Hard";
export type RiskLevel = "Low" | "Medium" | "High";

export type Category = (typeof categories)[number];

export type Issue = {
  slug: string;
  title: string;
  categoryId: Category["id"];
  platforms: Platform[];
  symptoms: string[];
  keywords: string[];
  difficulty: Difficulty;
  estimatedTimeMinutes: number;
  riskLevel: RiskLevel;
  safetyWarning?: string;
  escalationWarning?: string;
  steps: string[];
};

export const issues: Issue[] = [
  {
    slug: "slow-computer",
    title: "Slow computer",
    categoryId: "computer",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "Programs take a long time to open",
      "Mouse or keyboard input feels delayed",
      "Fan is loud and the device is warm",
    ],
    keywords: ["slow", "lag", "freezing", "performance", "speed", "stutter"],
    difficulty: "Medium",
    estimatedTimeMinutes: 20,
    riskLevel: "Low",
    steps: [
      "Save your work and close programs you are not using.",
      "Restart the computer to clear temporary files and refresh memory.",
      "Check available storage space and free up at least 10–15% of the drive.",
      "Review startup programs and disable items you do not need on boot.",
      "Run a trusted antivirus or system scan if the slowness is sudden.",
    ],
  },
  {
    slug: "computer-will-not-start",
    title: "Computer will not start",
    categoryId: "computer",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "Pressing the power button does nothing",
      "Screen remains black",
      "Lights or fans do not turn on",
    ],
    keywords: [
      "won't start",
      "will not start",
      "boot",
      "power",
      "black screen",
      "dead",
      "no power",
    ],
    difficulty: "Hard",
    estimatedTimeMinutes: 30,
    riskLevel: "Medium",
    safetyWarning:
      "Do not open the computer case unless you are authorized to perform hardware work.",
    escalationWarning:
      "Escalate to your IT team if you suspect a hardware fault or power supply failure.",
    steps: [
      "Make sure the power cable is firmly connected to the computer and outlet.",
      "Try a different wall outlet or power strip.",
      "Press and hold the power button for 10–15 seconds, then press it again.",
      "Disconnect all non-essential devices such as USB drives, docks, and external monitors.",
      "If the device still does not start, contact your IT support team.",
    ],
  },
  {
    slug: "computer-freezing",
    title: "Computer freezing",
    categoryId: "computer",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "The screen or cursor stops responding",
      "Apps freeze and become unclickable",
      "You have to force the computer off",
    ],
    keywords: [
      "freeze",
      "frozen",
      "not responding",
      "hang",
      "crashed",
      "stuck",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 20,
    riskLevel: "Low",
    safetyWarning:
      "Avoid forced power-offs while saving files; you may lose unsaved work.",
    steps: [
      "Wait a minute to see if the computer recovers on its own.",
      "For a single frozen app, try closing it normally or force-quit only that app.",
      "Save any open work and restart the computer.",
      "Check for pending operating-system updates and install them.",
      "If freezing is frequent, note when it happens and contact IT for deeper checks.",
    ],
  },
  {
    slug: "low-storage",
    title: "Low storage",
    categoryId: "computer",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "Disk space warning appears",
      "Cannot save new files",
      "Apps report there is not enough space",
    ],
    keywords: [
      "storage full",
      "low disk space",
      "not enough space",
      "disk almost full",
      "cannot save",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 15,
    riskLevel: "Low",
    steps: [
      "Empty the recycle bin or trash can to free up space.",
      "Delete or archive large files and downloads you no longer need.",
      "Clear temporary files and browser cache using built-in storage tools.",
      "Uninstall apps you no longer use from an approved app manager.",
      "If the device is still nearly full, ask IT about storage options or upgrades.",
    ],
  },
  {
    slug: "blue-screen-unexpected-restart",
    title: "Blue-screen or unexpected restart",
    categoryId: "computer",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "The screen turns blue with an error message",
      "The computer restarts without warning",
      "A kernel panic or crash report appears",
    ],
    keywords: [
      "blue screen",
      "bsod",
      "unexpected restart",
      "crash",
      "restarted",
      "kernel panic",
    ],
    difficulty: "Hard",
    estimatedTimeMinutes: 35,
    riskLevel: "Medium",
    safetyWarning:
      "Do not edit the registry, BIOS, or system firmware while troubleshooting.",
    escalationWarning:
      "Repeated crashes can indicate hardware or driver faults; escalate to IT.",
    steps: [
      "Save your work immediately and let the computer restart if it needs to.",
      "Note any error code or message shown before the restart.",
      "Check for and install pending operating-system updates.",
      "Restart the computer in safe mode only if you are comfortable doing so and IT approves.",
      "Contact IT with the error code if the problem keeps happening.",
    ],
  },
  {
    slug: "no-internet-connection",
    title: "No internet connection",
    categoryId: "network",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "Web pages will not load",
      "Apps show a connection error",
      "Network icon shows no connection",
    ],
    keywords: [
      "no internet",
      "offline",
      "connection",
      "network",
      "cannot browse",
      "no web",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 20,
    riskLevel: "Low",
    safetyWarning:
      "Only restart a router, modem or access point if you own it or your organization has authorized you to do so. On a workplace, school or shared network, contact IT before restarting any network equipment.",
    escalationWarning:
      "If other devices are also offline, the problem may be with the ISP or building network; contact IT.",
    steps: [
      "Check whether Wi-Fi is turned on or the Ethernet cable is securely connected.",
      "Try loading a website on another device to see if the problem is widespread.",
      "If you own the equipment or have authorization, restart the router or modem by unplugging it for 10 seconds, then plug it back in. On workplace, school or shared networks, contact IT instead of restarting it yourself.",
      "Reconnect to the network and test again.",
      "If wired and you are authorized, try a different Ethernet cable or wall jack. Escalate managed wiring to IT.",
    ],
  },
  {
    slug: "wi-fi-keeps-disconnecting",
    title: "Wi-Fi keeps disconnecting",
    categoryId: "network",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "Wi-Fi drops every few minutes",
      "Network connection is unstable",
      "Video calls freeze or buffer",
    ],
    keywords: [
      "wifi disconnect",
      "wi-fi dropping",
      "unstable wifi",
      "losing connection",
      "wireless",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 20,
    riskLevel: "Low",
    safetyWarning:
      "Only restart a router or access point if you own it or are authorized by your organization. On workplace, school or shared networks, ask IT before restarting network equipment.",
    steps: [
      "Move closer to the wireless access point.",
      "If you own or are authorized to restart the access point, restart it. On a shared or managed network, contact IT instead.",
      "Forget the network on your device and reconnect with the correct password.",
      "Remove sources of interference such as microwaves, baby monitors, or large metal objects.",
      "Check for software or driver updates for your wireless adapter.",
    ],
  },
  {
    slug: "slow-internet",
    title: "Slow internet",
    categoryId: "network",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "Web pages load very slowly",
      "Video streams buffer often",
      "Downloads take longer than usual",
    ],
    keywords: [
      "slow internet",
      "slow wifi",
      "buffering",
      "slow download",
      "connection slow",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 20,
    riskLevel: "Low",
    steps: [
      "Run a speed test on the same device to measure current performance.",
      "Compare the result on another device on the same network.",
      "Close apps or browser tabs that may be using bandwidth.",
      "Restart the computer or mobile device.",
      "If the network is shared or managed, contact IT before restarting any router or access point.",
    ],
  },
  {
    slug: "ethernet-not-working",
    title: "Ethernet not working",
    categoryId: "network",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "No connection when plugged in with a cable",
      "The Ethernet port light is off",
      "The computer says the cable is unplugged",
    ],
    keywords: [
      "ethernet",
      "wired not working",
      "cable unplugged",
      "no ethernet",
      "lan not working",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 15,
    riskLevel: "Low",
    steps: [
      "Make sure the cable clicks firmly into the computer and the wall jack.",
      "Try a different Ethernet cable if one is available.",
      "Test another wall jack or port if you are authorized to do so.",
      "Restart the computer and check the connection again.",
      "If the issue is in a managed office or school, report it to IT rather than adjusting wiring.",
    ],
  },
  {
    slug: "vpn-connection-problem",
    title: "VPN connection problem",
    categoryId: "network",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "VPN client will not connect",
      "VPN disconnects frequently",
      "You cannot reach internal resources while on VPN",
    ],
    keywords: ["vpn", "vpn not connecting", "vpn disconnects", "remote access"],
    difficulty: "Medium",
    estimatedTimeMinutes: 20,
    riskLevel: "Low",
    steps: [
      "Confirm you have an active internet connection without the VPN first.",
      "Close and reopen the VPN application.",
      "Check for an available VPN client update and install it from an approved source.",
      "Try connecting to a different VPN gateway if your app offers one.",
      "Contact IT with any error code or message; do not change VPN server settings yourself.",
    ],
  },
  {
    slug: "printer-showing-offline",
    title: "Printer showing offline",
    categoryId: "printer",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "Printer status says Offline",
      "Print jobs are not reaching the printer",
      "Printer icon has a warning symbol",
    ],
    keywords: [
      "printer offline",
      "printer not connected",
      "cannot print",
      "printer status",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 10,
    riskLevel: "Low",
    steps: [
      "Make sure the printer is powered on and has no error lights.",
      "Check that the printer is connected to the same network as your computer, or that the USB cable is secure.",
      "Restart the printer and wait for it to fully start up.",
      "In your computer's printer settings, set the printer to Online if it shows Offline.",
      "Try printing a test page.",
    ],
  },
  {
    slug: "print-job-stuck",
    title: "Print job stuck",
    categoryId: "printer",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "A document shows as printing but nothing happens",
      "Print queue has multiple pending jobs",
      "Printer is not responding to new jobs",
    ],
    keywords: [
      "print job stuck",
      "printer queue",
      "printing queue",
      "document not printing",
      "print spooler",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 10,
    riskLevel: "Low",
    steps: [
      "Open the print queue on your computer.",
      "Cancel or delete the stuck print job.",
      "Restart the printer.",
      "Restart your computer to clear the print queue.",
      "Resend the document you want to print.",
    ],
  },
  {
    slug: "paper-jam",
    title: "Paper jam",
    categoryId: "printer",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "The printer reports a paper jam",
      "Paper is crumpled or torn inside the printer",
      "The printer will not feed paper",
    ],
    keywords: ["paper jam", "jam", "paper stuck", "printer jam"],
    difficulty: "Easy",
    estimatedTimeMinutes: 10,
    riskLevel: "Low",
    steps: [
      "Turn the printer off and unplug it for safety.",
      "Open the printer cover and remove any visible paper slowly.",
      "Check for torn pieces of paper and remove them carefully.",
      "Reload paper correctly in the tray and avoid overfilling.",
      "Plug the printer back in, turn it on, and try printing again.",
    ],
  },
  {
    slug: "poor-print-quality",
    title: "Poor print quality",
    categoryId: "printer",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "Prints look faded or streaky",
      "Colors are incorrect or smudged",
      "There are lines or spots on the page",
    ],
    keywords: [
      "faded prints",
      "streaky prints",
      "poor print quality",
      "smudged",
      "lines on print",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 15,
    riskLevel: "Low",
    steps: [
      "Check ink or toner levels and replace cartridges if they are low.",
      "Use the printer's cleaning utility to clean the print heads or rollers.",
      "Make sure you are using the correct paper type and print settings.",
      "Print a test page to see if the issue improves.",
      "If quality is still poor after maintenance, contact IT or the printer supplier.",
    ],
  },
  {
    slug: "wrong-default-printer",
    title: "Wrong default printer",
    categoryId: "printer",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "Print jobs go to the wrong printer",
      "A printer you do not use is selected by default",
      "Documents print to a PDF or fax driver",
    ],
    keywords: [
      "default printer",
      "wrong printer",
      "prints to wrong printer",
      "printer selection",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 5,
    riskLevel: "Low",
    steps: [
      "Open your system settings and go to the Printers section.",
      "Identify the printer you want to use.",
      "Right-click or use the menu to set that printer as the default.",
      "Try printing a test page to confirm.",
      "If the wrong default keeps coming back, ask IT whether a policy manages printer settings.",
    ],
  },
  {
    slug: "email-not-syncing",
    title: "Email not syncing",
    categoryId: "email",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "New emails do not appear",
      "Sent folder is not up to date",
      "Calendar or contacts are missing changes",
    ],
    keywords: [
      "email not syncing",
      "emails not updating",
      "inbox not loading",
      "sync problem",
      "missing emails",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 10,
    riskLevel: "Low",
    safetyWarning:
      "Do not remove or re-add an email account without guidance from your IT team. Re-adding an account can delete local emails, calendar events or contacts that have not synced yet.",
    escalationWarning:
      "If your email is managed by your organization, or if you are unsure whether the account is managed, contact IT instead of changing settings.",
    steps: [
      "Check that you have an active internet connection.",
      "Refresh the inbox by pulling down or clicking the refresh button.",
      "Close the email app completely, then reopen it.",
      "Check that your account server settings, such as incoming and outgoing mail addresses, are correct. Do not enter your password into this tool.",
      "If the problem continues on a managed or uncertain account, contact your IT team before removing or re-adding the account.",
    ],
  },
  {
    slug: "cannot-send-email",
    title: "Cannot send email",
    categoryId: "email",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "Emails stay in the Outbox",
      "Send button returns an error",
      "Recipients report they did not receive the message",
    ],
    keywords: [
      "cannot send email",
      "email not sending",
      "outbox error",
      "send failed",
      "bounce",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 15,
    riskLevel: "Low",
    steps: [
      "Check your Outbox for any stuck messages and clear them if needed.",
      "Verify the recipient's email address is typed correctly.",
      "Confirm the attachment size is within your organization's limits.",
      "Check whether your mailbox is full or your account is blocked.",
      "Try sending a simple message without attachments.",
    ],
  },
  {
    slug: "not-receiving-email",
    title: "Not receiving email",
    categoryId: "email",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "Expected emails never arrive",
      "Senders say messages bounce back",
      "Only some emails are missing",
    ],
    keywords: [
      "not receiving email",
      "missing emails",
      "emails not arriving",
      "inbox empty",
      "email bounce",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 15,
    riskLevel: "Low",
    steps: [
      "Check your spam, junk, or clutter folders.",
      "Verify that your mailbox is not full.",
      "Check any inbox rules or filters that may move messages.",
      "Ask the sender to confirm the address and resend.",
      "If you still cannot receive emails, contact your IT or email provider.",
    ],
  },
  {
    slug: "attachment-problem",
    title: "Attachment problem",
    categoryId: "email",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "You cannot open an attachment",
      "An attachment is blocked or missing",
      "The attachment file size is too large",
    ],
    keywords: [
      "attachment",
      "cannot open attachment",
      "attachment too large",
      "attachment blocked",
      "file won't open",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 10,
    riskLevel: "Low",
    steps: [
      "Confirm the attachment file type is safe and supported.",
      "Ask the sender to resend the file if it appears broken or incomplete.",
      "Try opening the file on another device or app if you have permission.",
      "If the attachment is too large, ask the sender to use an approved file-sharing service.",
      "Never open unexpected attachments from unknown senders.",
    ],
  },
  {
    slug: "email-sign-in-problem",
    title: "Email sign-in problem",
    categoryId: "email",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "Email app keeps asking for a password",
      "You are told the password is wrong",
      "You cannot log in to webmail",
    ],
    keywords: [
      "email sign in",
      "cannot sign in",
      "password wrong",
      "email login",
      "authentication",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 15,
    riskLevel: "Medium",
    safetyWarning:
      "Never enter your password into HelpDesk First. Contact your IT team for managed accounts.",
    steps: [
      "Verify you are using the correct email address and password.",
      "Check that Caps Lock is off and you are typing carefully.",
      "Try signing in through the official webmail page from an approved link.",
      "If your password still fails, reset it through your organization's approved password tool.",
      "For managed or work accounts, contact IT instead of repeatedly entering your password.",
    ],
  },
  {
    slug: "application-will-not-open",
    title: "Application will not open",
    categoryId: "software",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "Double-clicking the app does nothing",
      "App opens and immediately closes",
      "An error appears at launch",
    ],
    keywords: [
      "app won't open",
      "application crash",
      "program not starting",
      "launch error",
      "software error",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 10,
    riskLevel: "Low",
    steps: [
      "Restart the application.",
      "Restart your computer and try again.",
      "Check for pending updates for the application.",
      "If the issue persists, reinstall the application from an approved source.",
      "Contact IT if the app is required for work and still will not open.",
    ],
  },
  {
    slug: "software-installation-problem",
    title: "Software installation problem",
    categoryId: "software",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "Installer fails before completing",
      "Error message appears during setup",
      "Installed app is missing features",
    ],
    keywords: [
      "install failed",
      "software installation",
      "setup error",
      "installer",
      "cannot install",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 20,
    riskLevel: "Medium",
    safetyWarning:
      "Only install software approved by your organization. Do not disable antivirus or security tools unless instructed by IT.",
    escalationWarning:
      "If the installer requires registry or system-level changes, escalate to IT instead of proceeding.",
    steps: [
      "Make sure your computer meets the minimum system requirements.",
      "Check that you have enough free disk space for the installation.",
      "Download the installer again in case the file is corrupted.",
      "Run the installer from an administrator account if prompted.",
      "If the installation still fails, contact IT with the exact error message.",
    ],
  },
  {
    slug: "application-frozen",
    title: "Application frozen",
    categoryId: "software",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "An app is not responding to clicks",
      "The app window is greyed out",
      "You cannot close the app normally",
    ],
    keywords: [
      "frozen app",
      "app not responding",
      "application hang",
      "software frozen",
      "force quit",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 5,
    riskLevel: "Low",
    steps: [
      "Wait a minute to see if the app recovers.",
      "Try closing the app through the normal close button.",
      "Force-quit the app only if you have unsaved work saved elsewhere.",
      "Reopen the app and open a test file or project.",
      "If the app freezes often, check for updates or contact IT.",
    ],
  },
  {
    slug: "update-failure",
    title: "Update failure",
    categoryId: "software",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "An app or system update keeps failing",
      "Update gets stuck at a percentage",
      "An error appears during an update",
    ],
    keywords: [
      "update failed",
      "update stuck",
      "update error",
      "cannot update",
      "patch failed",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 20,
    riskLevel: "Low",
    steps: [
      "Check your internet connection is stable.",
      "Make sure there is enough free storage for the update.",
      "Restart the device and try the update again.",
      "Install updates one at a time if multiple are queued.",
      "If the update is from your organization's management tool, contact IT before forcing it.",
    ],
  },
  {
    slug: "wrong-default-application",
    title: "Wrong default application",
    categoryId: "software",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "Files open in the wrong program",
      "Links open in an unexpected browser",
      "PDFs or documents use the wrong app",
    ],
    keywords: [
      "default app",
      "wrong app",
      "default browser",
      "open with",
      "file association",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 5,
    riskLevel: "Low",
    steps: [
      "Right-click a file and choose Open With or an app option.",
      "Set the correct application as the default for that file type.",
      "Check your system default apps settings for browsers, email, and files.",
      "Try opening the file again.",
      "If organization policy controls default apps, contact IT before changing them.",
    ],
  },
  {
    slug: "no-sound",
    title: "No sound",
    categoryId: "audio",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "No audio from speakers or headphones",
      "Volume icon shows a red cross or mute symbol",
      "Apps do not play sound",
    ],
    keywords: [
      "no sound",
      "no audio",
      "speaker not working",
      "volume muted",
      "headphones no sound",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 15,
    riskLevel: "Low",
    steps: [
      "Check that the volume is turned up and not muted.",
      "Make sure the correct playback device is selected.",
      "Test with a different set of headphones or speakers.",
      "Check for operating system audio driver updates.",
      "Restart the computer if the problem started recently.",
    ],
  },
  {
    slug: "camera-or-microphone-not-working",
    title: "Camera or microphone not working",
    categoryId: "audio",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "Video call camera is black",
      "Microphone does not pick up sound",
      "Apps cannot access the camera or mic",
    ],
    keywords: [
      "camera not working",
      "microphone not working",
      "cam not detected",
      "mic not working",
      "video call",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 15,
    riskLevel: "Low",
    steps: [
      "Check that no physical camera cover or mute switch is enabled.",
      "Allow the app to access the camera and microphone in your system privacy settings.",
      "Select the correct camera and microphone in the app's settings.",
      "Close other apps that may be using the camera.",
      "Restart the app and, if needed, your computer.",
    ],
  },
  {
    slug: "microphone-not-working",
    title: "Microphone not working",
    categoryId: "audio",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "No one can hear you on calls",
      "The mic icon is muted or not detected",
      "Voice recordings are silent",
    ],
    keywords: [
      "microphone",
      "mic not working",
      "no mic",
      "muted mic",
      "audio input",
    ],
    difficulty: "Easy",
    estimatedTimeMinutes: 10,
    riskLevel: "Low",
    steps: [
      "Check that a mute button or switch is not enabled.",
      "Select the correct microphone in your system sound settings.",
      "Test the microphone using the system's built-in test feature.",
      "Allow the calling or recording app permission to use the microphone.",
      "Try an external microphone to see if the issue is hardware-related.",
    ],
  },
  {
    slug: "bluetooth-headset-problem",
    title: "Bluetooth headset problem",
    categoryId: "audio",
    platforms: ["Windows", "Mac", "Mobile", "Other"],
    symptoms: [
      "Headset will not connect",
      "Audio cuts in and out",
      "Headset is paired but has no sound",
    ],
    keywords: [
      "bluetooth headset",
      "bluetooth not connecting",
      "headset disconnects",
      "wireless audio",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 15,
    riskLevel: "Low",
    steps: [
      "Make sure Bluetooth is turned on for both devices.",
      "Put the headset in pairing mode and reconnect it.",
      "Remove the headset from your device list and pair it again.",
      "Move closer to the computer or phone and away from interference.",
      "Charge or replace the headset battery and test again.",
    ],
  },
  {
    slug: "screen-sharing-problem",
    title: "Screen-sharing problem",
    categoryId: "audio",
    platforms: ["Windows", "Mac", "Other"],
    symptoms: [
      "Others see a black screen when you share",
      "Screen sharing option is greyed out",
      "Screen sharing is blurry or freezes",
    ],
    keywords: [
      "screen share",
      "screen sharing",
      "share screen not working",
      "black screen share",
      "presentation",
    ],
    difficulty: "Medium",
    estimatedTimeMinutes: 15,
    riskLevel: "Low",
    steps: [
      "Confirm the app has permission to record or share your screen.",
      "Close other apps or windows you do not need to share.",
      "Try sharing just one window instead of the full screen.",
      "Check your internet connection and close bandwidth-heavy apps.",
      "Restart the video-calling app and rejoin if sharing is still not working.",
    ],
  },
];
